### PR TITLE
Find library in env, package, then system

### LINKED ISSUE #37: lib-finding code should search package/lib first before searching system PATH
[The lib finding code](https://github.com/labstreaminglayer/liblsl-Python/blob/master/pylsl/pylsl.py#L1198-L1207) iterates through all possible combinations of library naming schemes. For each prefix-suffix combination, it first attempts the local dir then it attempts the system paths before moving on to the next combination.

I think this is the reason why more errors were reporting DLL errors with pylsl recently: it was finding old liblsl(32|64).dll on the PATH before it reached the correct naming scheme for the dll that's in the package/lib dir.

This should be changed so that it first searches through all combinations in the package/lib dir, then if that fails it searches at the system level. This requires a small refactor to so as to not duplicate the search code.

If someone else is in the mood to do that then you are more than welcome. Otherwise I'll add it to my lossy queue.

### PR DESCRIPTION
**Pull request by agricolab**
Fix #37
Add docstring and documentation to `find_liblsl_libraries`
Change search order, first go through prefix, suffix, and bitness locally then system-wide

### CODE REVIEW

**Comment by agricolab** [comment]
Sorry, i just saw that my visual code `black` autoformatter formatted it heavily. Give me a shout if you want that undone, @cboulay and i can open the PR fresh.

**Comment by cboulay** [comment]
I don’t mind the reformatting but can you separate it into another commit please?

**Comment by agricolab** [comment]
Okay, done. I added also
- Fix a bug in the raise RunTimeError, as `+` were missing to join the multilinestrings 
- Catch PYLSL_LIB pointing towards a non-existent file.

Sorry for the many force-pushes, apparently even my gedit was removing  trailing whitespace which resulted in too many diffs.
I guess it is really time to format pylsl.py.

**Comment by cboulay** [comment]
Sorry I took so long to get to this. It has been manually merged into master.

**Comment by agricolab** [comment]
No sweat. Happy if i could help.

**Pull request closed without merging**
